#
# Publish package to TestPyPi
#
# å‚è€ƒ: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
#
name: testpypi

on:
  push:
    branches:
      - release
      - develop

jobs:
  publish_to_testpypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Calculate next version number
        run: |
          export CURRENT_FULL_VERSION=`cat setup.cfg | sed -rn "s/version=(.*)/\1/p"`
          CURRENT_PATCH_VERSION=`echo ${CURRENT_FULL_VERSION} | sed -r 's/^.+\..+\.(.*)$/\1/'`
          NEXT_PATCH_VERSION=$(( ${CURRENT_PATCH_VERSION}+1 ))
          export NEXT_FULL_VERSION=`echo ${CURRENT_FULL_VERSION} | sed -r "s/^(.+)\.(.+)\..*$/\1.\2.${NEXT_PATCH_VERSION}/"`
          echo "Update: ${CURRENT_FULL_VERSION} -> ${NEXT_FULL_VERSION}"

      - name: Modify setup.cfg
        run: sed -i -e "s/version=.*/version=${NEXT_FULL_VERSION}/" setup.cfg

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Modify] **automated** setup.cfg (${CURRENT_FULL_VERSION} -> ${NEXT_FULL_VERSION})"

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution ðŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
